# Config file for automatic testing at travis-ci.org

language: python

python:
  - "3.6"
  - "3.5"
  - "3.3"
  - "2.7"
  - "2.6"
  - "pypy"

install:
  - pip install -e . pytest pytest-cov codecov

script:
  - pytest --cov=./tests

after_success:
  - codecov
