# Config file for automatic testing at travis-ci.org

language: python

python:
  - "3.6"
  - "3.5"
  - "3.3"
  - "2.7"
  - "2.6"
  - "pypy"

install:
  - pip install codecov coverage

script:
  - python setup.py test
  - coverage report

after_success:
  - codecov
