# Config file for automatic testing at travis-ci.org

language: python

python:
  - "3.8"
  - "3.7"
  - "3.6"
  - "3.5"
  - "pypy3"

install:
  - pip install -U pip
  - pip install -e .[optional]
  - pip install -U pytest pytest-cov pytest-console-scripts codecov flake8

script:
  - pytest --cov
  # ignore max complexity and line break after binary operator
  - flake8 tnefparse/ tests/ setup.py  --ignore=C901,W504
  # check max complexity, but do not enforce it
  - flake8 tnefparse/ tests/ setup.py  --count --exit-zero --max-complexity=10 --statistics

after_success:
  - codecov
